export type Block =
  | { type: "h2"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

export interface Post {
  slug: string;
  title: string;
  description: string;
  keyword: string;
  date: string;
  readMins: number;
  related?: string; // related calculator slug
  body: Block[];
}

export const POSTS: Post[] = [
  {
    slug: "how-far-can-a-deck-joist-span",
    related: "deck-joist-span-calculator",
    title: "How Far Can a Deck Joist Span?",
    description: "Maximum deck joist spans for 2x6, 2x8, 2x10 and 2x12 lumber at 12, 16 and 24 inch spacing, straight from the IRC R507.6 deck table.",
    keyword: "how far can a deck joist span",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "A deck joist's maximum span depends on three things: the joist size, how far apart the joists sit (the on-center spacing), and the species of lumber. The building code publishes these limits in IRC Table R507.6, and every plans examiner checks your drawings against it. Here is what those numbers actually look like." },
      { type: "h2", text: "Southern Pine joist spans (No. 2 grade)" },
      { type: "ul", items: [
        "2x6: 9'11\" at 12\" o.c., 9'0\" at 16\", 7'7\" at 24\"",
        "2x8: 13'1\" at 12\" o.c., 11'10\" at 16\", 9'8\" at 24\"",
        "2x10: 16'2\" at 12\" o.c., 14'0\" at 16\", 11'5\" at 24\"",
        "2x12: 18'0\" at 12\" o.c., 16'6\" at 16\", 13'6\" at 24\"",
      ] },
      { type: "p", text: "Douglas Fir-Larch and Hem-Fir span a little less than Southern Pine; cedar, redwood and the lighter pines span less again. Our calculator carries all three species groups and picks the smallest joist that clears your deck's projection automatically." },
      { type: "h2", text: "Why spacing matters so much" },
      { type: "p", text: "Closer joists share the load, so a 2x8 Southern Pine joist goes from 13'1\" at 12\" spacing down to 9'8\" at 24\". If your deck is just past a joist's limit, tightening the spacing one step is often cheaper than jumping up a lumber size, and it stiffens the deck underfoot." },
      { type: "h2", text: "A note on cantilevers" },
      { type: "p", text: "Joists can overhang the beam to form a small cantilever, but the IRC limits that overhang to one quarter of the actual back-span (R507.6.1). A deck that spans 12 ft to the beam can cantilever up to 3 ft past it, handy for stairs or a clean fascia line." },
    ],
  },
  {
    slug: "what-size-beam-for-a-deck",
    related: "deck-beam-span-calculator",
    title: "What Size Beam Does My Deck Need?",
    description: "How to pick a deck beam size from the IRC R507.5 table based on the joist span it carries and how far the beam must reach between posts.",
    keyword: "what size beam for a deck",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "A deck beam carries every joist that lands on it down to the posts. The bigger the area it supports and the farther it has to reach between posts, the beefier it has to be. IRC Table R507.5 ties those together: you look up the beam by the joist span it supports, and it tells you the maximum distance allowed between posts." },
      { type: "h2", text: "Beam span is driven by the joist span" },
      { type: "p", text: "This trips people up. A 3-ply 2x10 Southern Pine beam can span about 13 ft between posts when it carries 6-ft joists, but only about 10 ft when it carries 12-ft joists; same beam, more load, shorter reach. Always size the beam against the actual joist span it supports, not the deck's width." },
      { type: "h2", text: "Two-ply vs three-ply" },
      { type: "p", text: "Built-up beams are made by nailing or bolting 2x stock together. Adding a third ply to a beam of the same depth buys a meaningful jump in span. It's often the cheapest way to delete a post and a footing. A 3-2x10 reaches noticeably farther than a 2-2x10." },
      { type: "h2", text: "Don't forget the connections" },
      { type: "ul", items: [
        "Built-up beams must be fastened together per IRC R507.5.2 (a specific nail or bolt pattern).",
        "Posts to a dropped beam need a rated post cap, not just toe-nails.",
        "Where the beam sits on notched posts, the notch and bolts must follow R507.4.",
      ] },
      { type: "p", text: "Enter your deck in the calculator and it returns the recommended beam, the maximum post spacing, and how many posts your deck width needs, all from the R507.5 table." },
    ],
  },
  {
    slug: "deck-footing-size-and-depth",
    related: "deck-footing-calculator",
    title: "Deck Footing Size and Depth, Explained",
    description: "How to work out deck footing diameter from post load and soil bearing, and how deep footings must go below the frost line in your state.",
    keyword: "deck footing size",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "Footings do two jobs: spread the deck's weight over enough soil that it won't sink, and reach deep enough that frost can't lift them. Get either wrong and the deck racks, the ledger pulls, or doors stop closing after the first hard winter." },
      { type: "h2", text: "Footing size = load ÷ soil bearing" },
      { type: "p", text: "Each post carries a tributary slice of the deck: roughly the post spacing times half the joist span. Multiply that area by 50 psf (40 live + 10 dead) to get the load on the footing, then divide by your soil's bearing value to get the bearing area it needs. The IRC presumptive value for ordinary sand, silt or clay is 1,500 psf; gravel bears far more." },
      { type: "h2", text: "Depth follows the frost line" },
      { type: "p", text: "The bottom of the footing must sit below the local frost line so freezing soil can't heave it. That's about 12\" in the frost-free South, 36–48\" across the Midwest, and up to 60\" in the upper Midwest and New England. Even where the ground never freezes, you still need roughly 12\" to reach firm, undisturbed soil." },
      { type: "h2", text: "Get the footing inspected before you pour" },
      { type: "p", text: "Almost every jurisdiction requires an open-hole footing inspection before concrete goes in. It's the one part of the deck nobody can see afterward. Pick your state in the calculator to set the depth, and it sizes the footing diameter from your deck's actual loads." },
    ],
  },
  {
    slug: "how-to-build-deck-stairs",
    related: "deck-stair-calculator",
    title: "How to Build Code-Compliant Deck Stairs",
    description: "Lay out deck stairs to IRC R311.7: riser height, tread depth, stringer spacing and the total run you need from your deck height.",
    keyword: "deck stair calculator",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "Stairs are the part of a deck most likely to fail inspection, because the riser and tread dimensions are tightly controlled and easy to get wrong. The fix is to start from the total height and work backward to a legal riser." },
      { type: "h2", text: "The numbers that matter (IRC R311.7)" },
      { type: "ul", items: [
        "Maximum riser height: 7¾\". Minimum tread depth: 10\".",
        "Every riser in a flight must be within 3/8\" of the others; uniformity is strictly enforced.",
        "Minimum stair width: 36\". Minimum headroom: 6'8\".",
        "Four or more risers require a graspable handrail, 34–38\" above the nosings.",
      ] },
      { type: "h2", text: "Working out the layout" },
      { type: "p", text: "Take the total rise from the deck surface to the landing and divide by about 7.25\" to get a starting riser count, then round so no riser exceeds 7¾\". The number of treads is one less than the number of risers. At a 10–11\" run per tread, that gives you the total horizontal run you need to reserve at the bottom of the deck." },
      { type: "h2", text: "Stringers" },
      { type: "p", text: "Cut stringers are usually 2x12, and there's a limit on how far they can span unsupported: long flights need a mid-span support or solid (uncut) stringers. Our deck stair calculator turns your deck height into a full riser-and-tread layout in one step." },
    ],
  },
  {
    slug: "do-i-need-a-permit-to-build-a-deck",
    related: "deck-joist-span-calculator",
    title: "Do I Need a Permit to Build a Deck?",
    description: "When a deck needs a building permit, what the inspector checks, and how to prepare drawings that pass the first time.",
    keyword: "do i need a permit to build a deck",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "In almost every US jurisdiction, the answer is yes. A deck is a structure people stand on, often several feet in the air, attached to the house, so building departments want to see it before and during construction." },
      { type: "h2", text: "When a permit is required" },
      { type: "ul", items: [
        "Any deck attached to the house (because of the ledger connection).",
        "Any deck more than about 30\" above grade.",
        "Most freestanding decks above a small size threshold set locally.",
      ] },
      { type: "p", text: "Some areas exempt small, low, ground-level platforms, but check: the threshold varies and an unpermitted deck can derail a home sale." },
      { type: "h2", text: "What the inspector checks" },
      { type: "ul", items: [
        "Footing depth and size (inspected open, before the pour).",
        "Ledger attachment and flashing: the #1 cause of deck collapses.",
        "Joist and beam sizes against the IRC R507 span tables.",
        "Post connections, guard height and stair dimensions.",
      ] },
      { type: "h2", text: "Passing the first time" },
      { type: "p", text: "Submit a simple plan that names your joist size and spacing, beam size, post spacing, footing size and depth, and stair layout: exactly the outputs this calculator gives you. When your drawings cite the same R507 tables the examiner uses, approval is usually quick." },
    ],
  },
  {
    slug: "how-much-does-a-deck-cost",
    related: "deck-cost-calculator",
    title: "How Much Does It Cost to Build a Deck?",
    description: "Realistic 2026 deck cost ranges by size and material, where the money goes, and how much you save by doing your own framing.",
    keyword: "how much does a deck cost",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "Three things drive deck cost: size, material, and whether you build it yourself or hire a contractor. Knowing how those interact keeps your budget realistic before you ever buy lumber." },
      { type: "h2", text: "Typical ranges" },
      { type: "ul", items: [
        "DIY, pressure-treated pine: roughly $20–35 per square foot of deck.",
        "Contractor-built, pressure-treated: roughly $35–50 per square foot.",
        "Cedar or redwood, contractor-built: $45–60+ per square foot.",
        "Composite decking adds materially to the decking line but not the framing.",
      ] },
      { type: "p", text: "A 16x12 deck (192 sq ft) therefore runs from about $4,000 as a DIY pine build to $10,000+ contractor-installed in cedar." },
      { type: "h2", text: "Where the money goes" },
      { type: "p", text: "On a contractor-built deck, labor is roughly half the total, which is why doing your own framing is where the real savings are. Footings, stairs and railings are disproportionately expensive per square foot, so a simple rectangular deck close to the ground costs far less than a tall deck with multiple stair runs." },
      { type: "h2", text: "Estimate yours" },
      { type: "p", text: "Enter your deck size and species in the calculator for a build-cost range alongside a full framing plan, so your estimate is grounded in the actual lumber the deck needs." },
    ],
  },
  {
    slug: "deck-joist-spacing-12-vs-16-vs-24",
    related: "deck-joist-span-calculator",
    title: "Deck Joist Spacing: 12 vs 16 vs 24 Inches",
    description: "How joist spacing changes your maximum span, decking choice and deck stiffness, and when to use 12, 16 or 24 inch on-center.",
    keyword: "deck joist spacing",
    date: "2026-06-14",
    readMins: 4,
    body: [
      { type: "p", text: "Joist spacing (the on-center distance between joists) is one of the biggest levers you have on a deck. It changes how far the joists can span, what decking you can run, and how solid the deck feels underfoot." },
      { type: "h2", text: "16\" on-center is the default" },
      { type: "p", text: "Most decks frame at 16\" o.c. It balances span, lumber cost and stiffness, and it suits standard decking laid perpendicular to the joists. A 2x8 Southern Pine joist spans 11'10\" at 16\"." },
      { type: "h2", text: "When to go to 12\"" },
      { type: "ul", items: [
        "You're laying decking on a diagonal (the boards span a longer distance between joists).",
        "You want a stiffer, bounce-free deck.",
        "You need a bit more span out of the joist size you have on hand.",
      ] },
      { type: "h2", text: "When 24\" works" },
      { type: "p", text: "24\" o.c. uses less lumber and is allowed by the tables, but it shortens the span, can feel springy, and many composite deck boards require 16\" or even 12\" spacing, so always check the decking manufacturer's instructions. Run your numbers through the calculator at each spacing to see the trade-off." },
    ],
  },
  {
    slug: "how-many-footings-does-a-deck-need",
    related: "deck-footing-calculator",
    title: "How Many Footings Does a Deck Need?",
    description: "Work out the number of deck footings from your beam size, post spacing and deck width, and why bigger beams mean fewer holes to dig.",
    keyword: "how many footings for a deck",
    date: "2026-06-14",
    readMins: 4,
    body: [
      { type: "p", text: "The number of footings comes straight from how far your beam can span between posts. A beam that reaches farther needs fewer posts, and since every post needs a footing, beam size and footing count are directly linked." },
      { type: "h2", text: "Posts across the beam" },
      { type: "p", text: "Look up your beam's maximum post spacing in IRC Table R507.5, then divide your deck's width by it and round up. A 16-ft-wide deck with a beam good for 8 ft between posts needs three posts (two spans), so three footings along the beam, plus whatever the ledger and any stair posts require." },
      { type: "h2", text: "Fewer, bigger footings vs more, smaller ones" },
      { type: "ul", items: [
        "Upsizing the beam (e.g. 2-ply to 3-ply) can delete a post and a footing.",
        "Each footing still has to be big enough for the load its post carries; fewer posts means each footing carries more.",
        "On poor soil, you may need wider footings or more posts to keep bearing pressure in check.",
      ] },
      { type: "p", text: "The calculator reports the post count, spacing and the footing size each one needs, so you know exactly how many holes to dig and how big." },
    ],
  },
  {
    slug: "deck-ledger-board-attachment",
    related: "deck-footing-calculator",
    title: "Deck Ledger Board Attachment Done Right",
    description: "Why the ledger is the most important connection on a deck, how to fasten and flash it to code, and when a free-standing deck is the better call.",
    keyword: "deck ledger board attachment",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "Most catastrophic deck failures aren't the joists or the beam: they're the ledger pulling away from the house. The ledger is the board that bolts the deck to the building, and it carries half the deck's load straight into the wall framing." },
      { type: "h2", text: "Fasteners, not nails" },
      { type: "p", text: "The IRC (R507.9) requires a specific pattern of lag screws or through-bolts into the house's band joist; never nails, and never into just the sheathing. The bolt spacing depends on the joist span the ledger carries; longer joists put the bolts closer together." },
      { type: "h2", text: "Flashing is not optional" },
      { type: "ul", items: [
        "Water trapped behind a ledger rots the band joist until the bolts have nothing to hold.",
        "Flash over the top of the ledger and integrate it with the house's water-resistive barrier.",
        "Leave a small gap so water drains rather than wicking into the connection.",
      ] },
      { type: "h2", text: "When to go free-standing" },
      { type: "p", text: "If the band joist is questionable (engineered I-joists, a cantilevered floor, brick veneer, or stucco), a free-standing deck with its own beam and posts on the house side sidesteps the ledger problem entirely. It costs a little more in footings but removes the single biggest failure mode." },
    ],
  },
  {
    slug: "2x8-vs-2x10-deck-joists",
    related: "deck-joist-span-calculator",
    title: "2x8 vs 2x10 Deck Joists: Which Should You Use?",
    description: "When to step up from 2x8 to 2x10 deck joists: the span difference, the cost, and how spacing factors in.",
    keyword: "2x8 vs 2x10 deck joists",
    date: "2026-06-14",
    readMins: 4,
    body: [
      { type: "p", text: "Choosing between 2x8 and 2x10 joists usually comes down to one question: how far does the deck project out from the house? The bigger joist buys span, but it also costs more and raises the deck's framing height." },
      { type: "h2", text: "The span difference" },
      { type: "p", text: "In Southern Pine at 16\" on-center, a 2x8 spans 11'10\" and a 2x10 spans 14'0\", a bit over two extra feet. If your deck projects 12 ft, a 2x8 won't make it and you need the 2x10 (or you tighten the spacing to 12\", where the 2x8 reaches 13'1\")." },
      { type: "h2", text: "Cost and stiffness" },
      { type: "ul", items: [
        "2x10 lumber costs more per foot and is heavier to handle.",
        "A deeper joist is stiffer, so even within its allowable span the deck feels more solid.",
        "Deeper joists raise the framing, so check it still tucks under the door threshold.",
      ] },
      { type: "h2", text: "Let the table decide" },
      { type: "p", text: "Rather than guess, enter your projection and spacing into the calculator. It returns the smallest joist that legally clears your span, so you only pay for the lumber you actually need." },
    ],
  },
  {
    slug: "floating-deck-vs-attached-deck",
    related: "deck-footing-calculator",
    title: "Floating & Ground-Level Decks: What's Different",
    description: "How a floating (freestanding) deck differs from an attached deck: no ledger, different footings, and when you can skip the deep frost piers.",
    keyword: "floating deck",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "A floating or ground-level deck sits low to the ground and is not bolted to the house. Because there's no ledger (the connection that causes most deck failures), a freestanding deck sidesteps the single riskiest detail. But it changes how you handle posts and footings." },
      { type: "h2", text: "No ledger means no ledger problems" },
      { type: "p", text: "An attached deck hangs half its weight on a ledger lag-bolted into the house's band joist, which must be flashed and fastened exactly to code (IRC R507.9). A freestanding deck carries its whole load on its own beams and posts at both ends, so there's nothing to pull away from the house and no flashing to leak. That's why builders often go freestanding when the band joist is questionable: brick veneer, stucco, or engineered floor joists." },
      { type: "h2", text: "Footings: when can you skip the deep piers?" },
      { type: "ul", items: [
        "If the deck surface is 30\" or less above grade and the deck is freestanding, many jurisdictions allow it to 'float' on precast deck blocks or shallow pads instead of frost-depth piers, because a little seasonal movement won't hurt anything not tied to the house.",
        "Anything attached to the house, or taller, still needs footings below the frost line so the two structures move together.",
        "Local rules vary widely; always confirm with your building department before you decide to skip frost piers.",
      ] },
      { type: "h2", text: "Sizing is otherwise the same" },
      { type: "p", text: "Joists, beams and posts on a floating deck follow the same IRC R507 span tables as any other deck; the load doesn't change just because it's low. Use the calculator to size the framing, then decide on footings based on your height and whether it's attached. Guards are still required once you're over 30\" above grade." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}

const WEEK2_POSTS: Post[] = [
  {
    slug: "deck-board-spacing-guide",
    title: "Deck Board Spacing: What Gap Should You Leave?",
    description: "Standard 3/16 inch gap between deck boards allows drainage and prevents cupping. Here's how to set the right spacing for wood vs composite decking.",
    keyword: "deck board spacing",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "The gap between deck boards is not cosmetic — it controls drainage, allows expansion and prevents cupping. Get it wrong and you end up with a deck that holds water, warps or has uneven gaps after one season." },
      { type: "h2", text: "The standard 3/16 inch gap" },
      { type: "p", text: "For kiln-dried pressure-treated or cedar decking installed dry, leave a 3/16 inch gap between boards. This is roughly two nail widths and allows rainwater to run through without being wide enough to trap debris or pose a trip hazard." },
      { type: "h2", text: "Wet-installed pressure-treated lumber" },
      { type: "p", text: "Pressure-treated decking fresh from the lumber yard is wet and will shrink as it dries. If you install wet boards edge to edge (no gap), they will typically shrink to about a 1/4 inch gap over the first season. This is intentional — butting wet boards together lets the drying do the work. Check the moisture content of your boards; if they read above 19% on a moisture meter, butt them up tight." },
      { type: "h2", text: "Composite decking: follow the manufacturer" },
      { type: "p", text: "Composite decking expands with heat, not moisture. Most manufacturers specify gaps of 3/16 to 1/4 inch between boards end to end, and 3/16 inch edge to edge. The gap at the end of each board (the butt joint where two boards meet end-to-end over a joist) must match the manufacturer's spec — usually 1/4 inch — to allow thermal expansion without buckling." },
      { type: "h2", text: "Spacing at the house and fascia" },
      { type: "p", text: "Leave at least 1/2 inch between the deck boards and any adjacent house wall or fascia board so that moisture and debris don't accumulate in the gap. The IRC does not specify this clearance precisely, but most deck builders and manufacturers recommend at least 1/2 inch." },
    ],
  },
  {
    slug: "decking-screws-and-fasteners",
    title: "Decking Screws vs Hidden Fasteners: A Buyer's Guide",
    description: "Choosing between ring-shank screws, deck screws, composite screws and hidden fasteners? Here's how each performs on pressure-treated and composite decking.",
    keyword: "decking screws",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "The fastener you use on a deck is one of the most important decisions you will make — the wrong screw can corrode in a season, stain the decking or allow boards to pop up. Here is what to know before you buy." },
      { type: "h2", text: "Corrosion resistance is non-negotiable" },
      { type: "p", text: "All deck fasteners must be corrosion-resistant. The copper preservative in ACQ and CA pressure-treated lumber is chemically aggressive and will corrode plain steel screws within a year or two. The IRC requires that fasteners in contact with preservative-treated wood be either hot-dip galvanized, stainless steel, or specifically listed by the screw manufacturer as compatible with the preservative treatment used." },
      { type: "h2", text: "Deck screws vs structural screws" },
      { type: "p", text: "Deck screws (coarse thread, bugle head, typically #8 or #10 x 2.5\") are the standard fastener for attaching decking to joists. They hold adequately for the surface but are not engineered for structural connections. Structural screws (LedgerLOK, Titen HD, etc.) are different products with ICC approvals for specific structural load cases — ledger attachments, post bases and joist hangers." },
      { type: "h2", text: "Composite decking requires composite screws" },
      { type: "p", text: "Composite decking boards are denser and harder than wood. Standard wood deck screws can strip out or cause the composite material to spider-crack around the head. Use screws rated for composite decking — they have reverse-thread sections and modified head geometry that prevent mushrooming. Many composite manufacturers void the product warranty if you use non-approved fasteners." },
      { type: "h2", text: "Hidden fastener systems" },
      { type: "p", text: "Hidden fasteners clip into the groove on the edge of grooved composite or PVC decking boards and secure the board to the joist without any face screws visible. They produce a cleaner look and allow boards to expand and contract laterally without buckling. The downside: they are slower to install, cost more, and require grooved-edge boards. They also make it harder to replace a single damaged board later." },
      { type: "ul", items: [
        "For grooved composite or PVC: use hidden fasteners (e.g. Camo, Tiger Claw, EB-TY).",
        "For solid-edge composite: use composite-approved face screws, pre-drilling end boards.",
        "For pressure-treated or cedar: use hot-dip galvanized or stainless #8 or #10 deck screws.",
        "Always pre-drill the last 8 inches of any board near a cut end to prevent splitting.",
      ] },
    ],
  },
  {
    slug: "deck-design-load-requirements",
    title: "What Load Does a Deck Need to Be Designed For?",
    description: "Residential decks must carry 40 psf live load per the IBC. Here's what that means for framing and how snow load in your region may govern instead.",
    keyword: "deck load rating",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Every deck has a structural load limit, whether it is stamped on a permit drawing or not. Understanding that limit tells you what your deck can safely hold and when you need to think about reinforcement." },
      { type: "h2", text: "The 40 psf live load minimum" },
      { type: "p", text: "The International Residential Code (IRC) and International Building Code (IBC) require residential decks to be designed for a minimum 40 pounds per square foot (psf) live load. Live load is the variable load from people, furniture and portable equipment — everything that is not the permanent weight of the deck itself." },
      { type: "h2", text: "Dead load adds to the total" },
      { type: "p", text: "Dead load is the permanent weight of the deck structure: framing, decking, railings, a built-in grill or planters. A typical wood deck has a dead load of 10–15 psf; a composite deck with a concrete grill station can push 25+ psf. The framing must carry dead load + live load together. The code-minimum deck is designed for 40 psf live + 10 psf dead = 50 psf total." },
      { type: "h2", text: "Hot tubs and concentrated loads" },
      { type: "p", text: "A filled hot tub weighs 80–100 psf over its footprint. Standard deck framing is not adequate for this without reinforcement. If you plan to add a hot tub, the framing beneath it must be engineered specifically for that point load — typically closer joist spacing, a dedicated beam and larger footings." },
      { type: "h2", text: "Snow load may govern in northern states" },
      { type: "p", text: "In high-snow regions, the design snow load for an open deck equals or exceeds the 40 psf live load. When snow load governs, the deck framing must be designed for it — the snow load and the live load are not added together in most cases, since you assume the deck will not be occupied at full capacity during a snowstorm. Check the design requirements with your local building department." },
    ],
  },
  {
    slug: "deck-cantilever-rules-irc",
    title: "Deck Cantilever Rules: What the IRC Allows",
    description: "Deck joists can cantilever past the beam, but the IRC limits that overhang to one quarter of the actual back span. Here's the rule and common examples.",
    keyword: "deck cantilever rules",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "A deck cantilever is the portion of the deck that extends past the outer beam, with the joist hanging in the air beyond its last support. Cantilevering lets you push the deck edge out without adding a post and footing, but the IRC sets firm limits on how far you can go." },
      { type: "h2", text: "The one-quarter rule" },
      { type: "p", text: "IRC Section R507.6.1 limits the cantilever to one quarter of the allowable joist span. If your 2x10 Southern Pine joist is allowed to span 14 feet between ledger and beam, it can cantilever up to 14/4 = 3.5 feet past the beam. This is the absolute maximum; the joist size, spacing and species still govern the back-span, and you cannot exceed the smaller of the two limits." },
      { type: "h2", text: "Why the cantilever rule exists" },
      { type: "p", text: "A cantilevered joist creates an uplift force at the inner support (the beam). As more load is applied to the cantilevered end, the joist tries to lift off the beam at the opposite end. The connection at the beam must resist this uplift, and the joist itself must handle the negative bending moment over the beam — a stress that does not exist in a simply-supported span." },
      { type: "h2", text: "Common examples" },
      { type: "ul", items: [
        "2x10 Southern Pine at 16\" o.c. spans 14'0\" — maximum cantilever 3'6\".",
        "2x8 Southern Pine at 16\" o.c. spans 11'10\" — maximum cantilever 2'11\".",
        "2x12 Southern Pine at 24\" o.c. spans 13'6\" — maximum cantilever 3'4\".",
      ] },
      { type: "h2", text: "Don't forget the ledger side" },
      { type: "p", text: "The cantilever is measured from the outer face of the beam to the end of the joist. The back-span is measured from the beam to the ledger. Both must be within IRC limits, and the ratio of cantilever to back-span must not exceed 1:4. Our joist span calculator will flag if your cantilever exceeds the allowable based on the joist size and back-span you enter." },
    ],
  },
  {
    slug: "how-to-waterproof-a-deck",
    title: "How to Waterproof and Seal a Wood Deck",
    description: "Sealing protects wood decking from moisture, UV and fungal growth. Here's how to clean, sand and apply a deck waterproofing sealer correctly.",
    keyword: "deck waterproofing",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "An unsealed wood deck greys, checks and begins to rot within a few years. A properly waterproofed deck lasts decades. The work is not complicated, but the preparation matters as much as the product you use." },
      { type: "h2", text: "Clean before you seal" },
      { type: "p", text: "Power-wash the deck at 1200–1500 psi using a 25-degree tip. Work along the grain. If there is mildew, use a deck cleaner with oxalic acid or a diluted oxygen bleach solution and let it dwell for 15 minutes before rinsing. Let the deck dry completely — wait 48 hours after washing before applying any sealer." },
      { type: "h2", text: "Sand if needed" },
      { type: "p", text: "If the surface is rough, splintery or has raised grain, sand it lightly with 60–80 grit sandpaper on a pole sander. Wipe off sawdust before sealing. Sanding is not always necessary — if the boards are in good shape and just dirty, cleaning alone is enough." },
      { type: "h2", text: "Choose the right product" },
      { type: "ul", items: [
        "Water-repellent sealers: clear or lightly tinted, soak in rather than film. Easy to reapply yearly. Best for new decks.",
        "Stain-sealers: pigmented for UV protection and colour. Semi-transparent shows grain; solid hides it and covers greys.",
        "Oil-based products: penetrate deeply, excellent for hardwoods like ipe. Require mineral spirits for cleanup.",
        "Water-based products: lower VOC, faster dry time, clean up with water. Technology has improved significantly.",
      ] },
      { type: "h2", text: "Apply in the right conditions" },
      { type: "p", text: "Apply sealer when the temperature is between 50°F and 90°F with no rain expected for 24 hours. Direct sun can cause lap marks — work in the shade or in the morning. Brush sealer into gaps between boards and along the grain; a roller or pump sprayer followed by back-brushing gives even coverage. Two thin coats beat one thick coat." },
      { type: "h2", text: "How often to reseal" },
      { type: "p", text: "Clear water-repellent sealers need reapplication every 1–2 years. Semi-transparent stains typically last 2–3 years on horizontal surfaces. Solid stains last longest but peel rather than wear gracefully, which makes touch-ups more visible. The water bead test tells you when it's time: pour a cup of water on the deck — if it soaks in rather than beading, reseal." },
    ],
  },
  {
    slug: "common-deck-repairs",
    title: "The Most Common Deck Repairs (and When to DIY)",
    description: "Loose boards, rotted posts, corroded fasteners and failed ledger connections are the most frequent deck repairs. Here's how to diagnose and fix each one.",
    keyword: "deck repair",
    date: "2026-06-20",
    readMins: 7,
    body: [
      { type: "p", text: "Most deck problems are predictable and repairable before they become structural failures. Catching them early costs a few hundred dollars; missing them can cost thousands in framing replacement." },
      { type: "h2", text: "Loose or springy decking boards" },
      { type: "p", text: "Boards bounce underfoot when the fasteners have backed out or the wood has shrunk away from the screw head. Drive new screws an inch from the original holes; if the joist wood itself is punky (soft when probed with a knife), the joist needs sistering or replacement." },
      { type: "h2", text: "Rotted posts and footings" },
      { type: "p", text: "Post rot almost always starts at the bottom — at the post base connector, where water pools. Probe the post base with a screwdriver: if the wood is soft or hollow, the post is compromised. Short posts can be replaced by jacking the beam; tall posts in inaccessible locations may need a structural engineer to assess the repair scope." },
      { type: "h2", text: "Corroded fasteners" },
      { type: "p", text: "Green staining on decking boards under existing screws means the fasteners are corroding and leaching iron into the wood. Replace corroded screws with stainless steel or hot-dip galvanized screws rated for the preservative treatment used in your lumber. Check joist hanger nails and post base bolts too." },
      { type: "h2", text: "Failed ledger connections" },
      { type: "p", text: "The ledger is the highest-consequence connection on a deck. Signs of failure include the deck pulling away from the house, a gap opening at the ledger-to-house interface, or the deck feeling loose laterally. Do not attempt this repair without determining whether the original ledger attachment meets current code requirements. A failed ledger is the number-one cause of deck collapses." },
      { type: "h2", text: "Railing wobble" },
      { type: "p", text: "Railing posts must be tested to resist 200 pounds of lateral force at the top rail. A wobbly post is a life-safety issue, not just a cosmetic one. Most railing post failures trace back to inadequate fastening at the base — surface-mounted post bases without blocking, or toe-nailed posts. Rebuild the connection with proper through-bolts and blocking between joists." },
      { type: "h2", text: "When to call a structural engineer" },
      { type: "p", text: "Call a professional for: any rot in the ledger or main beam; multiple failed post bases; a deck that has shifted, settled or separated from the house; any repair that requires removing a load-bearing element. A deck inspection from a licensed contractor runs $150–$300 and can catch problems a homeowner would miss." },
    ],
  },
  {
    slug: "deck-ledger-flashing-guide",
    title: "Deck Ledger Flashing: Why It Matters and How to Do It",
    description: "Ledger flashing is the leading cause of deck failures when omitted or installed wrong. Here's the correct IRC and WFCM detail for sealing a deck ledger.",
    keyword: "deck ledger flashing",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "The ledger board attaches the deck to the house structure. Without proper flashing, water gets behind the ledger, soaks the house rim joist and band joist, and rots the framing that holds the deck up. This failure mode is responsible for the majority of deck collapses." },
      { type: "h2", text: "What the IRC requires" },
      { type: "p", text: "IRC Section R507.2 requires that the ledger be flashed to prevent water from entering the wall and that the flashing direct water to the exterior. The code does not specify a single approved method, but most jurisdictions accept the detail in the AWC Wood Frame Construction Manual (WFCM) as the prescriptive standard." },
      { type: "h2", text: "The correct flashing sequence" },
      { type: "ul", items: [
        "1. Cut a horizontal slot in the house cladding above where the ledger will sit.",
        "2. Install a piece of flashing (Z-flashing or self-adhesive membrane) that tucks into the cut and laps over the top of the ledger.",
        "3. Install the ledger and fasten it through the flashing into the rim joist.",
        "4. Install a second piece of flashing (cap flashing) that overlaps the first from above.",
        "5. Install housewrap lapping over the top flashing and sealed at all edges.",
      ] },
      { type: "h2", text: "Material options" },
      { type: "p", text: "Self-adhesive membrane flashing (Grace Ice & Water, Vycor) is the most reliable option — it bonds to the sheathing and wraps around fastener shanks to seal them. Metal Z-flashing is the traditional alternative and works well when properly installed, but it cannot seal around bolt shanks the way membrane can." },
      { type: "h2", text: "What not to do" },
      { type: "p", text: "Never caulk the top of the ledger and call it flashing. Caulk cracks, shrinks and allows water intrusion. Never install a ledger flat against vinyl siding without removing the siding and installing flashing behind it. Siding is a rain screen — it is not a waterproof barrier." },
    ],
  },
  {
    slug: "how-to-stain-a-deck",
    title: "How to Stain a Deck: Prep, Product and Process",
    description: "Staining a deck extends its life and restores colour. Here's how to clean, sand and prepare the surface, choose the right stain type and apply it evenly.",
    keyword: "how to stain a deck",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Staining a deck is one of the best returns on weekend maintenance. A good stain job adds years to the wood's life, reduces splintering and transforms a greying deck back to its original warmth. The staining itself takes a few hours — the preparation is what makes the difference." },
      { type: "h2", text: "Strip old stain if it is peeling" },
      { type: "p", text: "If the old stain is peeling, flaking or lapping in patches, you need to strip it before applying a new coat. Applying stain over failing old stain guarantees peeling in the new coat within one season. Use a deck stripper/brightener product, wait for it to work, and power-wash the deck clean. Let it dry 48 hours." },
      { type: "h2", text: "If the old stain is wearing evenly, clean and recoat" },
      { type: "p", text: "If the old stain is just faded but not peeling, a clean and recoat may be all you need. Power-wash at 1200–1500 psi, let dry, and apply a fresh coat of the same product (or a compatible product). Matching the old stain type — penetrating oil vs film-forming — matters; the two don't layer well together." },
      { type: "h2", text: "Stain types" },
      { type: "ul", items: [
        "Transparent stain: shows full wood grain; minimal pigment for UV protection; needs reapplication every 1–2 years.",
        "Semi-transparent stain: some colour, some grain visible; 2–3 year service life on decks.",
        "Semi-solid stain: more pigment, less grain visible; hides minor imperfections; 3–4 years.",
        "Solid stain: full colour coverage; longest life but peels when it fails, not wears.",
      ] },
      { type: "h2", text: "Application tips" },
      { type: "p", text: "Apply stain in the shade or on an overcast day. Start with a brush for end grain, board edges and tight spaces, then roll or spray the field area and back-brush while wet. Work 2–3 boards at a time so you don't get lap marks. Don't apply too thick — two thin coats for penetrating stains, one coat for most film-forming products. Wipe off excess penetrating stain after 10–15 minutes; don't let it puddle." },
    ],
  },
  {
    slug: "deck-blocks-vs-concrete-footings",
    title: "Deck Blocks vs Poured Concrete Footings",
    description: "Precast deck blocks are faster than poured footings but not right for every project. Here's when you can use them legally and when you need a real footing.",
    keyword: "deck foundation blocks",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Deck blocks — precast concrete blocks with a notch or cup on top — let you build a floating deck on grade without digging holes or pouring concrete. They are legal and common in many jurisdictions, but they come with important limitations." },
      { type: "h2", text: "What is a floating deck?" },
      { type: "p", text: "A floating deck is a freestanding deck that is not attached to the house and does not have footings that extend below the frost line. It sits on top of the ground on deck blocks or crushed stone pads. Because it is not connected to the house structure, it shifts slightly with frost and seasonal soil movement — and that is acceptable, because there is nothing attached to prevent it." },
      { type: "h2", text: "When deck blocks are permitted" },
      { type: "p", text: "Deck blocks are typically permitted for: low-to-grade decks (usually within 30 inches of grade) that are freestanding (not attached to the house ledger), used for non-primary structures, and in jurisdictions with minimal frost depth requirements. Many jurisdictions allow deck blocks for decks below a certain size or height without a permit — confirm with your local building department before starting." },
      { type: "h2", text: "When deck blocks are not enough" },
      { type: "ul", items: [
        "Attached decks must have footings below the frost line — if the deck moves, the house moves with it.",
        "Any deck tall enough to require a permit usually requires below-frost footings.",
        "Decks supporting a roof, pergola or any overhead structure need poured footings.",
        "Sites with poor drainage, expansive soils or high water tables need engineered footings.",
      ] },
      { type: "h2", text: "Deck block installation" },
      { type: "p", text: "Compact the soil under each block location, add a 2-inch base of crushed gravel for drainage, and set each block level. Snap a chalk line across the tops of the blocks; shim with patio block shims to achieve level. Don't put deck blocks on organic soil or mulch — they will settle unevenly." },
    ],
  },
  {
    slug: "pressure-treated-lumber-grades-for-decks",
    title: "Pressure-Treated Lumber Grades for Deck Building",
    description: "Pressure-treated lumber comes in several retention levels. Here's which grade to use for decking, joists, beams and below-grade posts in ground contact.",
    keyword: "pressure treated deck lumber",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Not all pressure-treated lumber is the same. The lumber is treated to different retention levels depending on the application, and using the wrong one is a code violation and a maintenance problem. Here is how to match the retention level to the part of the deck you are building." },
      { type: "h2", text: "Above-ground applications (UC3B)" },
      { type: "p", text: "Decking boards, joists, beams and railings that are exposed to weather but not in contact with the ground use Above-Ground designation lumber, typically labelled UC3B. These members are protected from rain but have intermittent wetting. The required preservative retention level for UC3B is lower than ground-contact." },
      { type: "h2", text: "Ground-contact applications (UC4A/UC4B)" },
      { type: "p", text: "Posts that are embedded in the ground, set in concrete, or continuously wet must be UC4A (standard ground contact) or UC4B (severe ground contact near salt water or high soil moisture). Using above-ground lumber in a ground-contact application is a common cause of rapid post rot — the treating chemical retention is insufficient to resist the constant moisture and microbial exposure." },
      { type: "h2", text: "How to read the tag" },
      { type: "p", text: "Every piece of pressure-treated lumber has a tag stapled to the end. It states the preservative type (ACQ, CA-C, MCQ, etc.), the retention level in pcf, and the use category (UC3B, UC4A, UC4B). Match the use category on the tag to the application. If the tag is missing or illegible, don't use that piece for a critical structural application." },
      { type: "h2", text: "Fastener compatibility" },
      { type: "p", text: "Modern copper-based preservatives (ACQ, CA-C) are corrosive to plain steel. Use only hot-dip galvanized or stainless fasteners, or fasteners with a coating specifically approved by the lumber manufacturer. Joist hangers and post bases must also be rated for use with ACQ/CA-treated lumber — look for the G185 or ZMAX rating on Simpson and USP connectors." },
    ],
  },
  {
    slug: "deck-maintenance-checklist",
    title: "Annual Deck Maintenance Checklist",
    description: "An annual inspection and cleaning keeps a wood deck safe and looking good for decades. Here's a room-by-room checklist for spring maintenance.",
    keyword: "deck maintenance",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Spring is the right time for an annual deck inspection — winter's freeze-thaw cycle has done its work, and a full season of use is coming. Walking through this checklist once a year catches problems while they are still small fixes." },
      { type: "h2", text: "Structural inspection" },
      { type: "ul", items: [
        "Probe post bases with a screwdriver: soft, punky wood means rot has started.",
        "Check the ledger: look for gaps at the house wall, staining or efflorescence, and test the ledger-to-house connection for movement.",
        "Bounce on joists at mid-span: excessive flex means the joist may be undersized, rotted or the load is too heavy.",
        "Check all joist hangers, post bases and beam-to-post connectors for rust, missing fasteners or loose nails.",
      ] },
      { type: "h2", text: "Decking surface inspection" },
      { type: "ul", items: [
        "Walk every board: loose, bouncy or cupped boards need to be re-fastened or replaced.",
        "Check for end grain rot on board ends, especially boards cut to fit and left unfinished.",
        "Look for surface checks (cracks along the grain) wider than 1/4 inch — these trap water.",
        "Pour water on the surface: if it soaks in rather than beading, the sealer is due.",
      ] },
      { type: "h2", text: "Railing safety check" },
      { type: "p", text: "Grab every railing post and push laterally with 20–30 pounds of force. There should be no noticeable movement. Test the top rail for continuous support. Check balusters for gaps wider than 4 inches (a 4-inch sphere must not pass through any opening). These are life-safety requirements — if the railing fails the test, repair before using the deck again." },
      { type: "h2", text: "Cleaning and sealing" },
      { type: "p", text: "Power-wash at low pressure (1200–1500 psi) along the grain. Clear all debris from between boards — trapped organic matter accelerates rot. Treat any mildew with a deck brightener. Once dry (48 hours minimum), do the bead test: if water soaks in, apply a fresh coat of sealer before the season starts." },
    ],
  },
  {
    slug: "wood-vs-composite-decking",
    title: "Wood vs Composite Decking: How to Choose",
    description: "Wood decking costs less up front; composite costs more but lasts longer and needs less maintenance. Here's a side-by-side comparison to guide your choice.",
    keyword: "wood deck vs composite deck",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Choosing between wood and composite decking is primarily a trade-off between upfront cost and long-term maintenance. Here is how they compare across the factors that matter most." },
      { type: "h2", text: "Upfront cost" },
      { type: "p", text: "Pressure-treated pine decking runs $2–$4 per linear foot for 5/4x6 boards. Cedar and redwood run $4–$7. Mid-grade composite decking (Trex Enhance, TimberTech Terrain) runs $4–$8 per linear foot. Premium composites (Trex Transcend, TimberTech Legacy) run $8–$15. Labor costs are similar regardless of material. Composite decking typically costs 20–50% more than PT pine for materials." },
      { type: "h2", text: "Long-term maintenance cost" },
      { type: "p", text: "Wood decking needs annual cleaning and sealing or staining, typically $50–$150 in materials per year for a 400 sq ft deck (or $300–$500+ if you hire out). Composite decking needs only annual cleaning with soap and water — no staining, no sealing. Over a 15-year period, the total cost of ownership often favors composite, especially when labor is accounted for." },
      { type: "h2", text: "Lifespan" },
      { type: "p", text: "A well-maintained pressure-treated deck can last 25–40 years. Untreated cedar or redwood lasts 15–25 years with good maintenance. Quality composite decking products carry 25–30 year warranties and typically outlast PT pine in practice because they do not rot, splinter or check." },
      { type: "h2", text: "Appearance and feel" },
      { type: "p", text: "Real wood feels and looks natural underfoot. It stays cooler in direct sun than composite (which can get quite hot on south-facing decks in summer). Composite decking has improved dramatically in appearance, with realistic wood grain textures and multiple colours, but knowledgeable observers can still tell the difference up close." },
      { type: "h2", text: "Which should you choose?" },
      { type: "ul", items: [
        "Budget build with regular maintenance: pressure-treated pine.",
        "Natural look, moderate budget, willing to seal every 1-2 years: cedar or redwood.",
        "Low maintenance priority, longer horizon, willing to spend more upfront: quality composite.",
        "Never want to think about maintenance again: capped PVC or capped composite.",
      ] },
    ],
  },
];

POSTS.push(...WEEK2_POSTS);
